### ISSUE TITLE
Why is "capex_mwh" being renamed to "gen_predetermined_storage_energy_mwh"?

### ISSUE THREAD

**Issue by gschivley** [JennyZheng-uh/PG_TO_SWTICH_refactor#1]
```
    # TODO: why is "capex_mwh" being renamed to "gen_predetermined_storage_energy_mwh"? 
```

https://github.com/gschivley/PG_TO_SWTICH_refactor/blob/fafb42874a78e95dca8fb3a198fe271235c360f7/conversion_functions.py#L413

This looks like it's incorrectly assigning the capex to existing energy capacity. The correct column for existing energy capacity is `Existing_Cap_MWh`

**Comment by JennyZheng-uh** [comment]
'''gen_predetermined_storage_energy_mwh[(g, bld_yr) in
    PREDETERMINED_GEN_BLD_YRS] is the amount of storage that has either been
    installed previously, or is slated for installation and is not a free
    decision variable. This is analogous to gen_predetermined_cap, but in
    units of energy of storage capacity (MWh) rather than power (MW).'''

This is what I found from switch, I do agree that 'capex_mwh' should not be the one to use, but are we sure 'Existing_Cap_MWh' is the one to use? How about 'Existing_Charge_Cap_MW'?
