### ISSUE TITLE
should use Existing_Cap_MW instead of Cap_Size for existing capacity

### ISSUE THREAD

**Issue by gschivley** [JennyZheng-uh/PG_TO_SWTICH_refactor#2]
```
    # TODO: should use Existing_Cap_MW instead of Cap_Size for existing capacity
```

https://github.com/gschivley/PG_TO_SWTICH_refactor/blob/fafb42874a78e95dca8fb3a198fe271235c360f7/conversion_functions.py#L414

**Comment by JennyZheng-uh** [comment]
Thanks, I double check docs and I think you are right.
